parameters:
  - name: deploy_to_dev
    type: boolean
    default: true
    displayName: "Deploy to DEV?"

trigger:
  branches:
    exclude:
      - master
      - test*
    include:
      - "main"
stages:
  - stage: Build
    jobs:
      - template: pipeline/jobs/build.yaml


  - ${{ if eq(parameters.deploy_to_dev, true) }}:
    - stage: DEV
      condition: succeeded('Build')
      jobs:
        - template: pipeline/jobs/deploy.yml
          parameters:
            stage: 'd'
          
 